### ISSUE TITLE
Logo contribution

### ISSUE THREAD

**Issue by reallinfo** [DKrakowczyk/smartHome#1]
Hello @DKrakowczyk I contribute to the open source community by designing logos. I noticed Smart Home didn't have a logo. so I designed a logo. I hope you like it. I will wait for feedback. Have a nice day!

![SMARTHOME](https://user-images.githubusercontent.com/36298335/55519903-85151780-5682-11e9-8ffa-34852be39090.jpg)

readme file view;

![smartt](https://user-images.githubusercontent.com/36298335/55519944-afff6b80-5682-11e9-9f19-2e6e96e70bd0.png)

**Comment by DKrakowczyk** [comment]
Hi there, thank you, it's amazing! I hope that we will be able to keep in touch with other projects. I'll link your profile in readme file. See you soon!

**Comment by reallinfo** [comment]
Thanks, of course, I would be happy to help for your other projects.  Would you like me to send you a pr for source files?

**Comment by DKrakowczyk** [comment]
Yeah, sure

**Comment by reallinfo** [comment]
I sent a pr. Have a nice day!

**Comment by DKrakowczyk** [comment]
Added link to your profile. Thanks a lot!

**Comment by reallinfo** [comment]
I'm closing this issue now. Best regards!
